// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gin} from '../models';
import {context} from '../models';

export function AddDocs(arg1:gin.Context):Promise<void>;

export function AllSettings(arg1:gin.Context):Promise<void>;

export function AutoStartEnabled():Promise<boolean>;

export function Bootstrap(arg1:gin.Context):Promise<void>;

export function BranchSession(arg1:gin.Context):Promise<void>;

export function ClipboardGetText():Promise<string>;

export function ClipboardSetText(arg1:string):Promise<boolean>;

export function CreateSession(arg1:gin.Context):Promise<void>;

export function CreateSkill(arg1:gin.Context):Promise<void>;

export function Ctx():Promise<context.Context>;

export function DecideApproval(arg1:gin.Context):Promise<void>;

export function DeleteDoc(arg1:gin.Context):Promise<void>;

export function DeleteProvider(arg1:gin.Context):Promise<void>;

export function DeleteSession(arg1:gin.Context):Promise<void>;

export function DeleteSkill(arg1:gin.Context):Promise<void>;

export function FollowUpMessage(arg1:gin.Context):Promise<void>;

export function ForceQuit():Promise<void>;

export function GetSession(arg1:gin.Context):Promise<void>;

export function Health(arg1:gin.Context):Promise<void>;

export function ImportSkills(arg1:gin.Context):Promise<void>;

export function ListApprovals(arg1:gin.Context):Promise<void>;

export function ListDocs(arg1:gin.Context):Promise<void>;

export function ListModels(arg1:gin.Context):Promise<void>;

export function ListProviders(arg1:gin.Context):Promise<void>;

export function ListSessions(arg1:gin.Context):Promise<void>;

export function ListSkills(arg1:gin.Context):Promise<void>;

export function ListTools(arg1:gin.Context):Promise<void>;

export function ModelCapability(arg1:gin.Context):Promise<void>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:string):Promise<string>;

export function Port():Promise<number>;

export function Quit(arg1:context.Context):Promise<void>;

export function ReindexDocs(arg1:gin.Context):Promise<void>;

export function RenameSession(arg1:gin.Context):Promise<void>;

export function RuntimeStatus(arg1:gin.Context):Promise<void>;

export function SearchKnowledge(arg1:gin.Context):Promise<void>;

export function SendMessage(arg1:gin.Context):Promise<void>;

export function ServerPort():Promise<number>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetDefaultProvider(arg1:gin.Context):Promise<void>;

export function SetServerPort(arg1:number):Promise<void>;

export function SetSessionModel(arg1:gin.Context):Promise<void>;

export function SetSessionPermission(arg1:gin.Context):Promise<void>;

export function SetSetting(arg1:gin.Context):Promise<void>;

export function SetStartupError(arg1:Error):Promise<void>;

export function Shutdown():Promise<void>;

export function SkillContent(arg1:gin.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StartupError():Promise<string>;

export function Stats(arg1:gin.Context):Promise<void>;

export function SteerMessage(arg1:gin.Context):Promise<void>;

export function StopRun(arg1:gin.Context):Promise<void>;

export function TestProvider(arg1:gin.Context):Promise<void>;

export function ToggleSkill(arg1:gin.Context):Promise<void>;

export function ToggleTool(arg1:gin.Context):Promise<void>;

export function UpdateProvider(arg1:gin.Context):Promise<void>;

export function UpsertProvider(arg1:gin.Context):Promise<void>;

export function WindowHide():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowShow():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
