// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKnowledgeDoc(arg1) {
  return window['go']['main']['App']['AddKnowledgeDoc'](arg1);
}

export function AddMcpServer(arg1) {
  return window['go']['main']['App']['AddMcpServer'](arg1);
}

export function AnswerInput(arg1, arg2) {
  return window['go']['main']['App']['AnswerInput'](arg1, arg2);
}

export function AppendMemory(arg1) {
  return window['go']['main']['App']['AppendMemory'](arg1);
}

export function CancelStream(arg1) {
  return window['go']['main']['App']['CancelStream'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CleanupMisreportedTokenUsage() {
  return window['go']['main']['App']['CleanupMisreportedTokenUsage']();
}

export function ClearMessages(arg1) {
  return window['go']['main']['App']['ClearMessages'](arg1);
}

export function CompactSession(arg1, arg2) {
  return window['go']['main']['App']['CompactSession'](arg1, arg2);
}

export function ContextUsage(arg1) {
  return window['go']['main']['App']['ContextUsage'](arg1);
}

export function CopyWorkspaceEntry(arg1, arg2) {
  return window['go']['main']['App']['CopyWorkspaceEntry'](arg1, arg2);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreatePetSprite(arg1) {
  return window['go']['main']['App']['CreatePetSprite'](arg1);
}

export function CreateProvider(arg1) {
  return window['go']['main']['App']['CreateProvider'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DecideApproval(arg1, arg2) {
  return window['go']['main']['App']['DecideApproval'](arg1, arg2);
}

export function DecideTrust(arg1) {
  return window['go']['main']['App']['DecideTrust'](arg1);
}

export function DeleteAgentProfile(arg1) {
  return window['go']['main']['App']['DeleteAgentProfile'](arg1);
}

export function DeleteCustomCommand(arg1) {
  return window['go']['main']['App']['DeleteCustomCommand'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteHook(arg1) {
  return window['go']['main']['App']['DeleteHook'](arg1);
}

export function DeleteKnowledgeDoc(arg1) {
  return window['go']['main']['App']['DeleteKnowledgeDoc'](arg1);
}

export function DeleteMemory(arg1) {
  return window['go']['main']['App']['DeleteMemory'](arg1);
}

export function DeleteMessage(arg1, arg2) {
  return window['go']['main']['App']['DeleteMessage'](arg1, arg2);
}

export function DeletePetSprite(arg1) {
  return window['go']['main']['App']['DeletePetSprite'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSessionArtifact(arg1) {
  return window['go']['main']['App']['DeleteSessionArtifact'](arg1);
}

export function DeleteSessions(arg1) {
  return window['go']['main']['App']['DeleteSessions'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteWorkspaceEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteWorkspaceEntry'](arg1, arg2);
}

export function EffectiveParams(arg1) {
  return window['go']['main']['App']['EffectiveParams'](arg1);
}

export function EmitReady(arg1) {
  return window['go']['main']['App']['EmitReady'](arg1);
}

export function EnsureSideConversation(arg1) {
  return window['go']['main']['App']['EnsureSideConversation'](arg1);
}

export function EventLog() {
  return window['go']['main']['App']['EventLog']();
}

export function Events() {
  return window['go']['main']['App']['Events']();
}

export function ExecutionRegistry() {
  return window['go']['main']['App']['ExecutionRegistry']();
}

export function ExportRunEvents(arg1) {
  return window['go']['main']['App']['ExportRunEvents'](arg1);
}

export function ForkSession(arg1, arg2) {
  return window['go']['main']['App']['ForkSession'](arg1, arg2);
}

export function GetAdminOverview() {
  return window['go']['main']['App']['GetAdminOverview']();
}

export function GetCircuitStatus() {
  return window['go']['main']['App']['GetCircuitStatus']();
}

export function GetContractVersion() {
  return window['go']['main']['App']['GetContractVersion']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetDashboardTrend(arg1) {
  return window['go']['main']['App']['GetDashboardTrend'](arg1);
}

export function GetDoc(arg1) {
  return window['go']['main']['App']['GetDoc'](arg1);
}

export function GetExecWhitelist() {
  return window['go']['main']['App']['GetExecWhitelist']();
}

export function GetFilePreviewURL(arg1) {
  return window['go']['main']['App']['GetFilePreviewURL'](arg1);
}

export function GetFolderTree(arg1) {
  return window['go']['main']['App']['GetFolderTree'](arg1);
}

export function GetGeneralSettings() {
  return window['go']['main']['App']['GetGeneralSettings']();
}

export function GetHealth() {
  return window['go']['main']['App']['GetHealth']();
}

export function GetKnowledgeDoc(arg1) {
  return window['go']['main']['App']['GetKnowledgeDoc'](arg1);
}

export function GetMcpRaw() {
  return window['go']['main']['App']['GetMcpRaw']();
}

export function GetMemoryOverview() {
  return window['go']['main']['App']['GetMemoryOverview']();
}

export function GetMemoryText() {
  return window['go']['main']['App']['GetMemoryText']();
}

export function GetPetConfig() {
  return window['go']['main']['App']['GetPetConfig']();
}

export function GetPetState() {
  return window['go']['main']['App']['GetPetState']();
}

export function GetProvider(arg1) {
  return window['go']['main']['App']['GetProvider'](arg1);
}

export function GetRuntimeStatus() {
  return window['go']['main']['App']['GetRuntimeStatus']();
}

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessionChange(arg1) {
  return window['go']['main']['App']['GetSessionChange'](arg1);
}

export function GetSessionGoal(arg1) {
  return window['go']['main']['App']['GetSessionGoal'](arg1);
}

export function GetSessionTodos(arg1) {
  return window['go']['main']['App']['GetSessionTodos'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetSideConversation(arg1) {
  return window['go']['main']['App']['GetSideConversation'](arg1);
}

export function GetTokenTrend(arg1) {
  return window['go']['main']['App']['GetTokenTrend'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWebSearchConfig() {
  return window['go']['main']['App']['GetWebSearchConfig']();
}

export function ImportKnowledgeFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportKnowledgeFile'](arg1, arg2, arg3);
}

export function ImportSkill(arg1) {
  return window['go']['main']['App']['ImportSkill'](arg1);
}

export function ImportSkillsZip(arg1) {
  return window['go']['main']['App']['ImportSkillsZip'](arg1);
}

export function ListAgentProfiles() {
  return window['go']['main']['App']['ListAgentProfiles']();
}

export function ListApprovalGrants() {
  return window['go']['main']['App']['ListApprovalGrants']();
}

export function ListAvailableModels() {
  return window['go']['main']['App']['ListAvailableModels']();
}

export function ListChatCommands(arg1) {
  return window['go']['main']['App']['ListChatCommands'](arg1);
}

export function ListCustomCommands() {
  return window['go']['main']['App']['ListCustomCommands']();
}

export function ListDocs() {
  return window['go']['main']['App']['ListDocs']();
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function ListFolders(arg1) {
  return window['go']['main']['App']['ListFolders'](arg1);
}

export function ListHooks() {
  return window['go']['main']['App']['ListHooks']();
}

export function ListKnowledgeByGroup(arg1) {
  return window['go']['main']['App']['ListKnowledgeByGroup'](arg1);
}

export function ListKnowledgeDocs() {
  return window['go']['main']['App']['ListKnowledgeDocs']();
}

export function ListKnowledgeGroups() {
  return window['go']['main']['App']['ListKnowledgeGroups']();
}

export function ListMcpServers() {
  return window['go']['main']['App']['ListMcpServers']();
}

export function ListMemory(arg1) {
  return window['go']['main']['App']['ListMemory'](arg1);
}

export function ListMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListMessages'](arg1, arg2, arg3);
}

export function ListPendingApprovals() {
  return window['go']['main']['App']['ListPendingApprovals']();
}

export function ListPetSprites() {
  return window['go']['main']['App']['ListPetSprites']();
}

export function ListProviderKinds() {
  return window['go']['main']['App']['ListProviderKinds']();
}

export function ListProviderPresets() {
  return window['go']['main']['App']['ListProviderPresets']();
}

export function ListProviderTiers() {
  return window['go']['main']['App']['ListProviderTiers']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListRuns(arg1) {
  return window['go']['main']['App']['ListRuns'](arg1);
}

export function ListSessionArtifacts(arg1, arg2) {
  return window['go']['main']['App']['ListSessionArtifacts'](arg1, arg2);
}

export function ListSessionChanges(arg1, arg2) {
  return window['go']['main']['App']['ListSessionChanges'](arg1, arg2);
}

export function ListSessions(arg1, arg2) {
  return window['go']['main']['App']['ListSessions'](arg1, arg2);
}

export function ListSettings() {
  return window['go']['main']['App']['ListSettings']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListTasks(arg1) {
  return window['go']['main']['App']['ListTasks'](arg1);
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function ListTrust() {
  return window['go']['main']['App']['ListTrust']();
}

export function ListWorkspaceDir(arg1, arg2) {
  return window['go']['main']['App']['ListWorkspaceDir'](arg1, arg2);
}

export function ListWorkspaceFiles(arg1) {
  return window['go']['main']['App']['ListWorkspaceFiles'](arg1);
}

export function OpenDirectoryDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1, arg2);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function PetMode() {
  return window['go']['main']['App']['PetMode']();
}

export function PetMove(arg1, arg2) {
  return window['go']['main']['App']['PetMove'](arg1, arg2);
}

export function PetToggleMode() {
  return window['go']['main']['App']['PetToggleMode']();
}

export function ReadLocalImage(arg1) {
  return window['go']['main']['App']['ReadLocalImage'](arg1);
}

export function ReadWorkspaceFile(arg1, arg2) {
  return window['go']['main']['App']['ReadWorkspaceFile'](arg1, arg2);
}

export function ReindexKnowledgeDoc(arg1) {
  return window['go']['main']['App']['ReindexKnowledgeDoc'](arg1);
}

export function ReloadMcpServers() {
  return window['go']['main']['App']['ReloadMcpServers']();
}

export function ReloadProvidersFromFile() {
  return window['go']['main']['App']['ReloadProvidersFromFile']();
}

export function RemoveMcpServer(arg1) {
  return window['go']['main']['App']['RemoveMcpServer'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RenameWorkspaceEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameWorkspaceEntry'](arg1, arg2, arg3);
}

export function ReplaceMemory(arg1) {
  return window['go']['main']['App']['ReplaceMemory'](arg1);
}

export function ResetCircuit(arg1) {
  return window['go']['main']['App']['ResetCircuit'](arg1);
}

export function ResolveTrust(arg1) {
  return window['go']['main']['App']['ResolveTrust'](arg1);
}

export function ResumeChat(arg1) {
  return window['go']['main']['App']['ResumeChat'](arg1);
}

export function RevealMcpFile() {
  return window['go']['main']['App']['RevealMcpFile']();
}

export function RevokeApprovalGrant(arg1) {
  return window['go']['main']['App']['RevokeApprovalGrant'](arg1);
}

export function RevokeTrust(arg1) {
  return window['go']['main']['App']['RevokeTrust'](arg1);
}

export function RollbackSessionChange(arg1) {
  return window['go']['main']['App']['RollbackSessionChange'](arg1);
}

export function SaveExecWhitelist(arg1) {
  return window['go']['main']['App']['SaveExecWhitelist'](arg1);
}

export function SaveGeneralSettings(arg1) {
  return window['go']['main']['App']['SaveGeneralSettings'](arg1);
}

export function SaveMcpRaw(arg1) {
  return window['go']['main']['App']['SaveMcpRaw'](arg1);
}

export function SavePetSpriteImage(arg1, arg2) {
  return window['go']['main']['App']['SavePetSpriteImage'](arg1, arg2);
}

export function SaveWebSearchConfig(arg1) {
  return window['go']['main']['App']['SaveWebSearchConfig'](arg1);
}

export function SearchFiles(arg1) {
  return window['go']['main']['App']['SearchFiles'](arg1);
}

export function SearchKnowledge(arg1, arg2) {
  return window['go']['main']['App']['SearchKnowledge'](arg1, arg2);
}

export function SearchMemory(arg1, arg2) {
  return window['go']['main']['App']['SearchMemory'](arg1, arg2);
}

export function SearchSessions(arg1) {
  return window['go']['main']['App']['SearchSessions'](arg1);
}

export function SendStream(arg1) {
  return window['go']['main']['App']['SendStream'](arg1);
}

export function SetAgentProfileEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAgentProfileEnabled'](arg1, arg2);
}

export function SetMcpServerEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetMcpServerEnabled'](arg1, arg2);
}

export function SetPetClickThrough(arg1) {
  return window['go']['main']['App']['SetPetClickThrough'](arg1);
}

export function SetSessionAgent(arg1, arg2) {
  return window['go']['main']['App']['SetSessionAgent'](arg1, arg2);
}

export function SetSessionArchived(arg1, arg2) {
  return window['go']['main']['App']['SetSessionArchived'](arg1, arg2);
}

export function SetSessionGoal(arg1, arg2) {
  return window['go']['main']['App']['SetSessionGoal'](arg1, arg2);
}

export function SetSessionModel(arg1, arg2) {
  return window['go']['main']['App']['SetSessionModel'](arg1, arg2);
}

export function SetSessionPermission(arg1, arg2) {
  return window['go']['main']['App']['SetSessionPermission'](arg1, arg2);
}

export function SetSessionPinned(arg1, arg2) {
  return window['go']['main']['App']['SetSessionPinned'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SetSkillEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetSkillEnabled'](arg1, arg2);
}

export function SetToolEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetToolEnabled'](arg1, arg2);
}

export function SettingValue(arg1, arg2) {
  return window['go']['main']['App']['SettingValue'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function SkipApproval(arg1) {
  return window['go']['main']['App']['SkipApproval'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function SteerSession(arg1, arg2) {
  return window['go']['main']['App']['SteerSession'](arg1, arg2);
}

export function SubmitTask(arg1) {
  return window['go']['main']['App']['SubmitTask'](arg1);
}

export function TestHook(arg1) {
  return window['go']['main']['App']['TestHook'](arg1);
}

export function TestProviderConnect(arg1) {
  return window['go']['main']['App']['TestProviderConnect'](arg1);
}

export function ToggleSessionTodo(arg1, arg2) {
  return window['go']['main']['App']['ToggleSessionTodo'](arg1, arg2);
}

export function TruncateMessages(arg1, arg2) {
  return window['go']['main']['App']['TruncateMessages'](arg1, arg2);
}

export function TrustRoots() {
  return window['go']['main']['App']['TrustRoots']();
}

export function UpdateFolder(arg1, arg2) {
  return window['go']['main']['App']['UpdateFolder'](arg1, arg2);
}

export function UpdateKnowledgeDoc(arg1, arg2) {
  return window['go']['main']['App']['UpdateKnowledgeDoc'](arg1, arg2);
}

export function UpdatePetConfig(arg1) {
  return window['go']['main']['App']['UpdatePetConfig'](arg1);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['main']['App']['UpdateProvider'](arg1, arg2);
}

export function UpdateSessionWorkspace(arg1, arg2) {
  return window['go']['main']['App']['UpdateSessionWorkspace'](arg1, arg2);
}

export function UpdateSkill(arg1, arg2) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2);
}

export function UploadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3, arg4);
}

export function UploadFileData(arg1) {
  return window['go']['main']['App']['UploadFileData'](arg1);
}

export function UploadPetSprite(arg1, arg2) {
  return window['go']['main']['App']['UploadPetSprite'](arg1, arg2);
}

export function UpsertAgentProfile(arg1) {
  return window['go']['main']['App']['UpsertAgentProfile'](arg1);
}

export function UpsertCustomCommand(arg1) {
  return window['go']['main']['App']['UpsertCustomCommand'](arg1);
}

export function UpsertHook(arg1) {
  return window['go']['main']['App']['UpsertHook'](arg1);
}

export function WikiOverview(arg1) {
  return window['go']['main']['App']['WikiOverview'](arg1);
}

export function WikiPage(arg1, arg2) {
  return window['go']['main']['App']['WikiPage'](arg1, arg2);
}
