// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDocs(arg1) {
  return window['go']['main']['App']['AddDocs'](arg1);
}

export function AllSettings(arg1) {
  return window['go']['main']['App']['AllSettings'](arg1);
}

export function AutoStartEnabled() {
  return window['go']['main']['App']['AutoStartEnabled']();
}

export function Bootstrap(arg1) {
  return window['go']['main']['App']['Bootstrap'](arg1);
}

export function BranchSession(arg1) {
  return window['go']['main']['App']['BranchSession'](arg1);
}

export function ClipboardGetText() {
  return window['go']['main']['App']['ClipboardGetText']();
}

export function ClipboardSetText(arg1) {
  return window['go']['main']['App']['ClipboardSetText'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function CreateSkill(arg1) {
  return window['go']['main']['App']['CreateSkill'](arg1);
}

export function Ctx() {
  return window['go']['main']['App']['Ctx']();
}

export function DecideApproval(arg1) {
  return window['go']['main']['App']['DecideApproval'](arg1);
}

export function DeleteDoc(arg1) {
  return window['go']['main']['App']['DeleteDoc'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function FetchModels(arg1) {
  return window['go']['main']['App']['FetchModels'](arg1);
}

export function FollowUpMessage(arg1) {
  return window['go']['main']['App']['FollowUpMessage'](arg1);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GetModelConfig(arg1) {
  return window['go']['main']['App']['GetModelConfig'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function Health(arg1) {
  return window['go']['main']['App']['Health'](arg1);
}

export function ImportSkills(arg1) {
  return window['go']['main']['App']['ImportSkills'](arg1);
}

export function ListApprovals(arg1) {
  return window['go']['main']['App']['ListApprovals'](arg1);
}

export function ListDocs(arg1) {
  return window['go']['main']['App']['ListDocs'](arg1);
}

export function ListModelConfigs(arg1) {
  return window['go']['main']['App']['ListModelConfigs'](arg1);
}

export function ListModels(arg1) {
  return window['go']['main']['App']['ListModels'](arg1);
}

export function ListProviders(arg1) {
  return window['go']['main']['App']['ListProviders'](arg1);
}

export function ListSessions(arg1) {
  return window['go']['main']['App']['ListSessions'](arg1);
}

export function ListSkills(arg1) {
  return window['go']['main']['App']['ListSkills'](arg1);
}

export function ListTools(arg1) {
  return window['go']['main']['App']['ListTools'](arg1);
}

export function ModelCapability(arg1) {
  return window['go']['main']['App']['ModelCapability'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function Port() {
  return window['go']['main']['App']['Port']();
}

export function Quit(arg1) {
  return window['go']['main']['App']['Quit'](arg1);
}

export function ReindexDocs(arg1) {
  return window['go']['main']['App']['ReindexDocs'](arg1);
}

export function RenameSession(arg1) {
  return window['go']['main']['App']['RenameSession'](arg1);
}

export function RuntimeStatus(arg1) {
  return window['go']['main']['App']['RuntimeStatus'](arg1);
}

export function SearchKnowledge(arg1) {
  return window['go']['main']['App']['SearchKnowledge'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function ServerPort() {
  return window['go']['main']['App']['ServerPort']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetDefaultProvider(arg1) {
  return window['go']['main']['App']['SetDefaultProvider'](arg1);
}

export function SetServerPort(arg1) {
  return window['go']['main']['App']['SetServerPort'](arg1);
}

export function SetSessionModel(arg1) {
  return window['go']['main']['App']['SetSessionModel'](arg1);
}

export function SetSessionPermission(arg1) {
  return window['go']['main']['App']['SetSessionPermission'](arg1);
}

export function SetSetting(arg1) {
  return window['go']['main']['App']['SetSetting'](arg1);
}

export function SetStartupError(arg1) {
  return window['go']['main']['App']['SetStartupError'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function SkillContent(arg1) {
  return window['go']['main']['App']['SkillContent'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StartupError() {
  return window['go']['main']['App']['StartupError']();
}

export function Stats(arg1) {
  return window['go']['main']['App']['Stats'](arg1);
}

export function SteerMessage(arg1) {
  return window['go']['main']['App']['SteerMessage'](arg1);
}

export function StopRun(arg1) {
  return window['go']['main']['App']['StopRun'](arg1);
}

export function TestProvider(arg1) {
  return window['go']['main']['App']['TestProvider'](arg1);
}

export function ToggleSkill(arg1) {
  return window['go']['main']['App']['ToggleSkill'](arg1);
}

export function ToggleTool(arg1) {
  return window['go']['main']['App']['ToggleTool'](arg1);
}

export function UpdateProvider(arg1) {
  return window['go']['main']['App']['UpdateProvider'](arg1);
}

export function UpsertModelConfig(arg1) {
  return window['go']['main']['App']['UpsertModelConfig'](arg1);
}

export function UpsertProvider(arg1) {
  return window['go']['main']['App']['UpsertProvider'](arg1);
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowShow() {
  return window['go']['main']['App']['WindowShow']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
