// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {event} from '../models';
import {core} from '../models';
import {llm} from '../models';
import {context} from '../models';

export function AddKnowledgeDoc(arg1:domain.KnowledgeDocREQ):Promise<domain.KnowledgeDocRESP>;

export function AddMcpServer(arg1:domain.McpServerREQ):Promise<domain.McpServerRESP>;

export function AnswerInput(arg1:string,arg2:domain.AnswerInputREQ):Promise<void>;

export function AppendMemory(arg1:domain.MemoryWriteREQ):Promise<void>;

export function CancelStream(arg1:string):Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function CleanupMisreportedTokenUsage():Promise<Record<string, any>>;

export function ClearMessages(arg1:string):Promise<void>;

export function CompactSession(arg1:string,arg2:domain.CompactREQ):Promise<domain.CompactResultRESP>;

export function ContextUsage(arg1:string):Promise<domain.ContextUsageRESP>;

export function CopyWorkspaceEntry(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CreateFolder(arg1:domain.FolderREQ):Promise<domain.FolderRESP>;

export function CreatePetSprite(arg1:domain.PetSpriteREQ):Promise<domain.PetSpriteRESP>;

export function CreateProvider(arg1:domain.AiProviderREQ):Promise<domain.AiProviderRESP>;

export function CreateSession(arg1:domain.ChatSessionREQ):Promise<domain.ChatSessionRESP>;

export function DecideApproval(arg1:string,arg2:domain.DecideApprovalREQ):Promise<void>;

export function DecideTrust(arg1:domain.WorkspaceTrustREQ):Promise<domain.WorkspaceTrustRESP>;

export function DeleteAgentProfile(arg1:string):Promise<void>;

export function DeleteCustomCommand(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<Record<string, any>>;

export function DeleteFolder(arg1:string):Promise<Record<string, any>>;

export function DeleteHook(arg1:string):Promise<void>;

export function DeleteKnowledgeDoc(arg1:string):Promise<void>;

export function DeleteMemory(arg1:domain.MemoryDeleteREQ):Promise<void>;

export function DeleteMessage(arg1:string,arg2:string):Promise<void>;

export function DeletePetSprite(arg1:string):Promise<Record<string, any>>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSessionArtifact(arg1:string):Promise<void>;

export function DeleteSessions(arg1:Array<string>):Promise<domain.BatchDeleteResult>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteWorkspaceEntry(arg1:string,arg2:string):Promise<Record<string, any>>;

export function EffectiveParams(arg1:string):Promise<domain.EffectiveParamsRESP>;

export function EmitReady(arg1:number):Promise<void>;

export function EnsureSideConversation(arg1:string):Promise<domain.ChatSessionRESP>;

export function EventLog():Promise<event.RunEventLog>;

export function Events():Promise<event.Bus>;

export function ExecutionRegistry():Promise<core.ExecutionRegistry>;

export function ExportRunEvents(arg1:string):Promise<string>;

export function ForkSession(arg1:string,arg2:domain.ForkSessionREQ):Promise<domain.ChatSessionRESP>;

export function GetAdminOverview():Promise<domain.AdminOverviewRESP>;

export function GetCircuitStatus():Promise<Array<domain.ProviderCircuitRESP>>;

export function GetContractVersion():Promise<number>;

export function GetDashboardStats():Promise<domain.DashboardStatsRESP>;

export function GetDashboardTrend(arg1:number):Promise<domain.DashboardTrendRESP>;

export function GetDoc(arg1:string):Promise<domain.DocDetailRESP>;

export function GetExecWhitelist():Promise<Array<string>>;

export function GetFilePreviewURL(arg1:string):Promise<Record<string, any>>;

export function GetFolderTree(arg1:string):Promise<Array<domain.FolderTreeNode>>;

export function GetGeneralSettings():Promise<Record<string, any>>;

export function GetHealth():Promise<domain.HealthInfo>;

export function GetKnowledgeDoc(arg1:string):Promise<domain.KnowledgeDocRESP>;

export function GetMcpRaw():Promise<domain.McpRawRESP>;

export function GetMemoryOverview():Promise<domain.MemoryOverviewRESP>;

export function GetMemoryText():Promise<string>;

export function GetPetConfig():Promise<domain.PetConfigRESP>;

export function GetPetState():Promise<string>;

export function GetProvider(arg1:string):Promise<domain.AiProviderRESP>;

export function GetRuntimeStatus():Promise<domain.RuntimeStatusRESP>;

export function GetServerPort():Promise<number>;

export function GetSession(arg1:string):Promise<domain.ChatSessionRESP>;

export function GetSessionChange(arg1:string):Promise<domain.FileChangeDetailRESP>;

export function GetSessionGoal(arg1:string):Promise<domain.GoalRESP>;

export function GetSessionTodos(arg1:string):Promise<domain.TodoStateRESP>;

export function GetSetting(arg1:string):Promise<domain.SystemSettingRESP>;

export function GetSideConversation(arg1:string):Promise<domain.ChatSessionRESP>;

export function GetTokenTrend(arg1:domain.TokenTrendREQ):Promise<domain.TokenTrendRESP>;

export function GetVersion():Promise<domain.VersionInfo>;

export function GetWebSearchConfig():Promise<domain.WebSearchConfigRESP>;

export function ImportKnowledgeFile(arg1:string,arg2:string,arg3:string):Promise<domain.KnowledgeDocRESP>;

export function ImportSkill(arg1:domain.SkillREQ):Promise<domain.SkillRESP>;

export function ImportSkillsZip(arg1:string):Promise<Record<string, any>>;

export function ListAgentProfiles():Promise<Array<domain.AgentProfileRESP>>;

export function ListApprovalGrants():Promise<Array<domain.ApprovalGrantRESP>>;

export function ListAvailableModels():Promise<Array<domain.AvailableModelRESP>>;

export function ListChatCommands(arg1:string):Promise<domain.CommandListRESP>;

export function ListCustomCommands():Promise<Array<domain.UserCommandRESP>>;

export function ListDocs():Promise<Array<domain.DocItemRESP>>;

export function ListFiles():Promise<Array<domain.FileRESP>>;

export function ListFolders(arg1:string):Promise<Array<domain.FolderRESP>>;

export function ListHooks():Promise<Array<domain.UserHookRESP>>;

export function ListKnowledgeByGroup(arg1:string):Promise<Array<domain.KnowledgeDocRESP>>;

export function ListKnowledgeDocs():Promise<Array<domain.KnowledgeDocRESP>>;

export function ListKnowledgeGroups():Promise<Array<string>>;

export function ListMcpServers():Promise<Array<domain.McpServerRESP>>;

export function ListMemory(arg1:string):Promise<domain.MemoryListRESP>;

export function ListMessages(arg1:string,arg2:number,arg3:number):Promise<domain.MessageListRESP>;

export function ListPendingApprovals():Promise<Array<domain.ApprovalPendingRESP>>;

export function ListPetSprites():Promise<Array<domain.PetSpriteRESP>>;

export function ListProviderKinds():Promise<domain.ProviderKindsRESP>;

export function ListProviderPresets():Promise<Array<llm.ProviderPreset>>;

export function ListProviderTiers():Promise<Array<domain.ProviderTier>>;

export function ListProviders():Promise<Array<domain.AiProviderRESP>>;

export function ListRuns(arg1:domain.RunRecordListREQ):Promise<domain.RunRecordListRESP>;

export function ListSessionArtifacts(arg1:string,arg2:number):Promise<domain.ArtifactListRESP>;

export function ListSessionChanges(arg1:string,arg2:number):Promise<domain.FileChangeListRESP>;

export function ListSessions(arg1:number,arg2:number):Promise<domain.SessionListRESP>;

export function ListSettings():Promise<Array<domain.SystemSettingRESP>>;

export function ListSkills():Promise<Array<domain.SkillRESP>>;

export function ListTasks(arg1:number):Promise<domain.ChatTaskListRESP>;

export function ListTools():Promise<Array<domain.ToolMeta>>;

export function ListTrust():Promise<Array<domain.WorkspaceTrustRESP>>;

export function ListWorkspaceDir(arg1:string,arg2:string):Promise<domain.WorkspaceListRESP>;

export function ListWorkspaceFiles(arg1:string):Promise<Array<domain.WorkspaceFileItem>>;

export function OpenDirectoryDialog(arg1:string,arg2:string):Promise<string>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFileDialog(arg1:string,arg2:string):Promise<string>;

export function PetMode():Promise<boolean>;

export function PetMove(arg1:number,arg2:number):Promise<Record<string, any>>;

export function PetToggleMode():Promise<Record<string, any>>;

export function ReadLocalImage(arg1:string):Promise<string>;

export function ReadWorkspaceFile(arg1:string,arg2:string):Promise<string>;

export function ReindexKnowledgeDoc(arg1:string):Promise<void>;

export function ReloadMcpServers():Promise<domain.McpReloadRESP>;

export function ReloadProvidersFromFile():Promise<Record<string, any>>;

export function RemoveMcpServer(arg1:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<domain.ChatSessionRESP>;

export function RenameWorkspaceEntry(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ReplaceMemory(arg1:domain.MemoryReplaceREQ):Promise<void>;

export function ResetCircuit(arg1:string):Promise<Record<string, any>>;

export function ResolveTrust(arg1:string):Promise<domain.TrustResolveRESP>;

export function ResumeChat(arg1:string):Promise<domain.SendStreamResult>;

export function RevealMcpFile():Promise<void>;

export function RevokeApprovalGrant(arg1:string):Promise<void>;

export function RevokeTrust(arg1:string):Promise<void>;

export function RollbackSessionChange(arg1:string):Promise<void>;

export function SaveExecWhitelist(arg1:Array<string>):Promise<Array<string>>;

export function SaveGeneralSettings(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SaveMcpRaw(arg1:domain.McpRawREQ):Promise<domain.McpReloadRESP>;

export function SavePetSpriteImage(arg1:string,arg2:string):Promise<domain.PetSpriteRESP>;

export function SaveWebSearchConfig(arg1:domain.WebSearchConfigRESP):Promise<Record<string, any>>;

export function SearchFiles(arg1:string):Promise<Array<domain.FileRESP>>;

export function SearchKnowledge(arg1:string,arg2:number):Promise<Array<domain.KnowledgeHitRESP>>;

export function SearchMemory(arg1:string,arg2:number):Promise<Array<domain.MemoryEntryRESP>>;

export function SearchSessions(arg1:domain.SessionSearchREQ):Promise<domain.SessionListRESP>;

export function SendStream(arg1:domain.SendStreamREQ):Promise<domain.SendStreamResult>;

export function SetAgentProfileEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetMcpServerEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetPetClickThrough(arg1:domain.PetClickThroughREQ):Promise<Record<string, any>>;

export function SetSessionAgent(arg1:string,arg2:domain.SetSessionAgentREQ):Promise<void>;

export function SetSessionArchived(arg1:string,arg2:domain.SessionArchiveREQ):Promise<domain.ChatSessionRESP>;

export function SetSessionGoal(arg1:string,arg2:domain.GoalREQ):Promise<domain.GoalRESP>;

export function SetSessionModel(arg1:string,arg2:domain.ChatSessionModelREQ):Promise<domain.ChatSessionRESP>;

export function SetSessionPermission(arg1:string,arg2:domain.ChatSessionPermissionREQ):Promise<domain.ChatSessionRESP>;

export function SetSessionPinned(arg1:string,arg2:domain.SessionPinREQ):Promise<domain.ChatSessionRESP>;

export function SetSetting(arg1:string,arg2:string):Promise<domain.SystemSettingRESP>;

export function SetSkillEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetToolEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SettingValue(arg1:context.Context,arg2:string):Promise<string>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function SkipApproval(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function SteerSession(arg1:string,arg2:domain.SteerREQ):Promise<domain.SteerResultRESP>;

export function SubmitTask(arg1:domain.ChatTaskREQ):Promise<domain.ChatTaskDO>;

export function TestHook(arg1:string):Promise<domain.HookTestRESP>;

export function TestProviderConnect(arg1:string):Promise<void>;

export function ToggleSessionTodo(arg1:string,arg2:string):Promise<domain.TodoStateRESP>;

export function TruncateMessages(arg1:string,arg2:domain.TruncateMessagesREQ):Promise<void>;

export function TrustRoots():Promise<Array<string>>;

export function UpdateFolder(arg1:string,arg2:domain.FolderREQ):Promise<domain.FolderRESP>;

export function UpdateKnowledgeDoc(arg1:string,arg2:domain.KnowledgeDocREQ):Promise<domain.KnowledgeDocRESP>;

export function UpdatePetConfig(arg1:domain.PetConfigREQ):Promise<domain.PetConfigRESP>;

export function UpdateProvider(arg1:string,arg2:domain.AiProviderREQ):Promise<domain.AiProviderRESP>;

export function UpdateSessionWorkspace(arg1:string,arg2:string):Promise<domain.ChatSessionRESP>;

export function UpdateSkill(arg1:string,arg2:domain.SkillREQ):Promise<domain.SkillRESP>;

export function UploadFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<domain.FileRESP>;

export function UploadFileData(arg1:domain.UploadDataREQ):Promise<domain.FileRESP>;

export function UploadPetSprite(arg1:string,arg2:string):Promise<domain.PetSpriteRESP>;

export function UpsertAgentProfile(arg1:domain.AgentProfileREQ):Promise<domain.AgentProfileRESP>;

export function UpsertCustomCommand(arg1:domain.UserCommandREQ):Promise<domain.UserCommandRESP>;

export function UpsertHook(arg1:domain.UserHookREQ):Promise<domain.UserHookRESP>;

export function WikiOverview(arg1:string):Promise<domain.WikiOverviewRESP>;

export function WikiPage(arg1:string,arg2:string):Promise<domain.WikiPageRESP>;
